# [overlay]
# overlay_cmd = "${lib.getExe pkgs.kitty} +kitten icat --fit height --align left --no-trailing-newline ${./cat.png}"
# overlay_trimmed_lines = 0
[general]
default_module = "app"               # module to run when no prefix is matched
empty_module = "app"                 # run with an empty prompt
exec_cmd = "zsh -c"                  # exec command of your shell
vi_mode = false                      # set true to use vi keybinds, false emacs keybinds
esc_to_abort = true                  # useful for vi users
cheatsheet_entry = "?"               # when prompted, will show a list of configured modules
cheatsheet_viewer = "less -R; clear" # command to show cheatsheet; through piping stdout
clear_screen_after_execution = false
loop_mode = false                    # don't quit after executing a module, useful with scratchpads; stderr is hidden in loop mode
external_editor = "nvim"             # if set, press ctrl+x ctrl+ee (or v in vi normal mode) to edit prompt in the specified program
delay_startup = 0                    # sometimes the otter runs too fast even before the terminal window is ready; this slows it down by milliseconds; useful when chafa image is skewed

[interface]
# use three quotes to write longer codes
# header = """
#   \x1b[1;38;2;203;166;247m$USER@$HOST\x1b[0m
# 	"""
header = '''

  '''
header_cmd = '' # run a command and print stdout above the header
header_cmd_trimmed_lines = 0 # remove trailing lines from header_cmd output, in case of some programs appending excessive empty lines
place_holder = "execute" # at the input field
suggestion_mode = "list" # available options: list, hint
separator = """
$( \
    text="                      "; \
    printf "\u001B[0;90m$text \
    $(printf -v line '%*s' \"$(( COLUMNS - $(printf "$text" | wc -m) - 3 ))\" ''; printf '%s' \"${line// /─}\")" \
)"""
footer = "" # add a line after suggestion list
suggestion_lines = 7 # 0 to disable suggestions and tab completion
list_prefix = "  "
selection_prefix = "\u001B[31;1m "
prefix_padding = 3 # format prefixes to have a uniformed width
default_module_message = "  \u001B[33mlaunch\u001B[0m app" # shown when the default module is in use
empty_module_message = "" # shown when the empty module is in use
customized_list_order = false # false to list modules alphabetically; true to list as per the configured order in the below [[modules]] section
indicator_with_arg_module = " * " # the sign showing whether a module should run with an argument
indicator_no_arg_module = " "
# below color options affect all modules; per-module coloring can be configured using ansi codes individually
prefix_color = "\u001B[33m"
description_color = "\u001B[39m"
place_holder_color = "\u001B[30m"
hint_color = "\u001B[30m"         # suggestion color in hint mode
# move the interface rightward or downward
# move_interface_right = 21
move_interface_down = 0

[[modules]]
description = "programs"
prefix = "app"
cmd = """
hyprctl dispatch 'hl.dsp.window.resize({x = 700, y = 700, window = activewindow})' &&
hyprctl dispatch 'hl.dsp.window.center({window = activewindow})'&&
hyprctl dispatch "hl.dsp.exec_cmd('$(fsel --no-exec)')"
"""

[[modules]]
description = "bluetooth"
prefix = "bl"
cmd = """
hyprctl dispatch 'hl.dsp.window.resize({x = 650, y = 400, window = activewindow})' &&
hyprctl dispatch 'hl.dsp.window.center({window = activewindow})'&&
bluetui
"""

[[modules]]
description = "nixos wiki"
prefix = "nw"
cmd = """
hyprctl dispatch "hl.dsp.exec_cmd('helium-browser --new-window https://wiki.nixos.org/w/index.php?search={}')"
"""
with_argument = true
url_encode = true
unbind_proc = true

[[modules]]
description = "nixpkgs"
prefix = "nix"
cmd = """
hyprctl dispatch "hl.dsp.exec_cmd('helium-browser --new-window https://search.nixos.org/packages?query={}')"
"""
with_argument = true
url_encode = true
unbind_proc = true

[[modules]]
description = "jellyfin"
prefix = "jf"
cmd = """
hyprctl dispatch  'hl.dsp.exec_cmd("kitty --class jf-tui -e jellyfin-tui", {workspace = "special:music"})'
"""

[[modules]]
description = "youtube"
prefix = "y"
cmd = """
hyprctl dispatch "hl.dsp.exec_cmd('helium-browser --new-window https://www.youtube.com')"
"""
with_argument = false
url_encode = true
unbind_proc = true

[[modules]]
description = "whatsapp"
prefix = "w"
cmd = """
hyprctl dispatch "hl.dsp.exec_cmd('helium-browser --new-window https://web.whatsapp.com')"
"""
with_argument = false
url_encode = true
unbind_proc = true
