# BEGIN_KITTY_THEME
# Eldritch
include current-theme.conf
# END_KITTY_THEME
# include ~/.cache/wal/colors-kitty.conf
background_opacity 0.99
allow_remote_control yes
listen_on unix:/tmp/kitty
# remote_control_password "kitty-rc-password" ls
remote_control_password "" ls
allow_remote_control yes
#shell fish
editor nvim
cursor_trail 3
cursor_trail_decay 0.1 0.4
